# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.IntegerField()),
                ('appname', models.CharField(max_length=50)),
                ('hdfs_root_dir', models.CharField(max_length=50)),
                ('hdfs_cluster', models.CharField(max_length=50)),
                ('appowner', models.CharField(max_length=50)),
                ('appowner_email', models.CharField(max_length=50)),
                ('servicecontact', models.CharField(max_length=50)),
                ('servicecontact_email', models.CharField(max_length=50)),
                ('hdfs_stage', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hdfs_cluster', models.CharField(max_length=50)),
                ('backupqueue', models.CharField(max_length=50)),
                ('backupsetsize', models.BigIntegerField()),
                ('namenode', models.CharField(max_length=50)),
            ],
        ),
    ]
