# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadoop_backup_catalog', '0002_backupsets'),
    ]

    operations = [
        migrations.CreateModel(
            name='backupoperations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.IntegerField()),
                ('boid', models.IntegerField()),
                ('backup_type', models.CharField(max_length=9)),
                ('last_backup_timestamp', models.DateField()),
                ('num_archives', models.IntegerField()),
                ('start_time', models.DateField()),
                ('completion_time', models.DateField()),
                ('elapsed_seconds', models.IntegerField()),
                ('status', models.CharField(max_length=24)),
            ],
        ),
    ]
