# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadoop_backup_catalog', '0003_backupoperations'),
    ]

    operations = [
        migrations.CreateModel(
            name='backupfile_exceptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.IntegerField()),
                ('boid', models.IntegerField()),
                ('bsid', models.IntegerField()),
                ('file_name', models.CharField(max_length=1000)),
                ('file_size', models.IntegerField()),
                ('resent', models.CharField(max_length=12)),
                ('r_boid', models.IntegerField()),
                ('r_bsid', models.IntegerField()),
                ('exception_reason', models.CharField(max_length=64)),
                ('resent_reason', models.CharField(max_length=64)),
            ],
        ),
    ]
