# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hadoop_backup_catalog', '0004_backupfile_exceptions'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='backupfile_exceptions',
            table='backupfile_exceptions',
        ),
    ]
