# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hadoop_backup_catalog', '0005_auto_20180705_1103'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='backupoperations',
            table='backupoperations',
        ),
        migrations.AlterModelTable(
            name='backupsets',
            table='backupsets',
        ),
    ]
