# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadoop_backup_catalog', '0006_auto_20180705_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='backuparchives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.IntegerField()),
                ('boid', models.IntegerField()),
                ('bsid', models.IntegerField()),
                ('backup_type', models.CharField(max_length=9)),
                ('file_name', models.CharField(max_length=1000)),
                ('filename_offset', models.IntegerField()),
                ('length', models.IntegerField()),
                ('handle', models.CharField(max_length=256)),
                ('backupfile_offset', models.IntegerField()),
                ('status', models.CharField(max_length=24)),
            ],
            options={
                'db_table': 'backuparchives',
            },
        ),
        migrations.CreateModel(
            name='exclusion_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.IntegerField()),
                ('excl_list', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'exclusion_list',
            },
        ),
    ]
