# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadoop_backup_catalog', '0007_backuparchives_exclusion_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='backuparchives_raw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.IntegerField()),
                ('boid', models.IntegerField()),
                ('bsid', models.IntegerField()),
                ('file_name', models.CharField(max_length=1000)),
                ('file_size', models.IntegerField()),
                ('status', models.CharField(max_length=24)),
                ('handle_raw', models.CharField(max_length=200)),
                ('last_seen', models.DateField()),
            ],
            options={
                'db_table': 'backuparchives_raw',
            },
        ),
    ]
