# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadoop_backup_catalog', '0008_backuparchives_raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupoperations',
            name='completion_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='backupoperations',
            name='last_backup_timestamp',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='backupoperations',
            name='start_time',
            field=models.DateField(null=True),
        ),
    ]
