# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadoop_backup_catalog', '0011_auto_20180705_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backuparchives_raw',
            name='appid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='backuparchives_raw',
            name='boid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='backuparchives_raw',
            name='bsid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='backuparchives_raw',
            name='file_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='backuparchives_raw',
            name='handle_raw',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='backuparchives_raw',
            name='last_seen',
            field=models.DateField(null=True),
        ),
    ]
