# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadoop_backup_catalog', '0012_auto_20180705_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backuparchives_raw',
            name='appid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='backuparchives_raw',
            name='boid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='backuparchives_raw',
            name='bsid',
            field=models.IntegerField(),
        ),
    ]
