# Generated by Django 2.0.7 on 2018-08-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadoop_backup_catalog', '0014_auto_20180719_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup_recovery',
            name='recovery_state',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='backup_recovery',
            name='staging_directory',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='backup_recovery',
            name='status',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
