# Generated by Django 2.0.7 on 2018-08-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadoop_backup_catalog', '0015_auto_20180806_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup_recovery',
            name='recovery_job_id',
            field=models.IntegerField(null=True),
        ),
    ]
