# Generated by Django 2.0.7 on 2018-08-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadoop_backup_catalog', '0019_delete_backup_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='backup_reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.IntegerField(null=True)),
                ('boid', models.IntegerField(null=True)),
                ('last_backup_timestamp', models.DateTimeField(null=True)),
                ('num_files', models.IntegerField()),
            ],
            options={
                'db_table': 'backup_reports',
                'managed': (False,),
            },
        ),
    ]
